# Generated by Django 5.2.5 on 2025-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
