# Generated by Django 5.2.5 on 2025-08-20 01:50

from django.db import migrations

def add_video_urls_to_exercises(apps, schema_editor):
    """
    Find existing exercises and update them with their video URLs.
    """
    Exercise = apps.get_model('workouts', 'Exercise')

    # A dictionary mapping exercise names to their video file paths
    exercise_videos = {
        'Push-up': '/videos/pushup.mp4',
        'Squat': '/videos/squat.mp4',
        'Plank': '/videos/plank.mp4',
        'Lunge': '/videos/lunge.mp4',
        'Dumbbell Row': '/videos/dumbbell_row.mp4',
        'Dumbbell Bench Press': '/videos/dumbbell_press.mp4',
        'Goblet Squat': '/videos/goblet_squat.mp4',
        'Dumbbell Fly': '/videos/dumbbell_fly.mp4', # From your other migration
    }

    for name, url in exercise_videos.items():
        try:
            # Find the exercise by name and update it
            exercise_to_update = Exercise.objects.get(name=name)
            exercise_to_update.video_url = url
            exercise_to_update.save()
        except Exercise.DoesNotExist:
            # This allows the migration to run even if an exercise was deleted
            pass



class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercise_video_url'),
    ]

    operations = [
    ]
