# Generated by Django 5.2.5 on 2025-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_seed_progress_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='workouts_completed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
