# Generated by Django 5.2.5 on 2025-08-20 02:36

from django.db import migrations

def create_sample_meals(apps, schema_editor):
    Meal = apps.get_model('diet', 'Meal')
    Meal.objects.bulk_create([
        Meal(name='Oatmeal with Berries', meal_type='breakfast', calories=350, protein_g=10, carbs_g=60, fat_g=8, ingredients='...', instructions='...'),
        Meal(name='Scrambled Eggs with Spinach', meal_type='breakfast', calories=300, protein_g=20, carbs_g=5, fat_g=22, ingredients='...', instructions='...'),
        Meal(name='Grilled Chicken Salad', meal_type='lunch', calories=450, protein_g=40, carbs_g=20, fat_g=25, ingredients='...', instructions='...'),
        Meal(name='Quinoa Bowl with Veggies', meal_type='lunch', calories=400, protein_g=15, carbs_g=60, fat_g=12, ingredients='...', instructions='...'),
        Meal(name='Salmon with Asparagus', meal_type='dinner', calories=500, protein_g=45, carbs_g=15, fat_g=30, ingredients='...', instructions='...'),
        Meal(name='Lentil Soup', meal_type='dinner', calories=380, protein_g=20, carbs_g=55, fat_g=8, ingredients='...', instructions='...'),
        Meal(name='Greek Yogurt with Almonds', meal_type='snack', calories=200, protein_g=18, carbs_g=15, fat_g=8, ingredients='...', instructions='...'),
        Meal(name='Apple with Peanut Butter', meal_type='snack', calories=250, protein_g=8, carbs_g=30, fat_g=14, ingredients='...', instructions='...'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_meal_mealplan'),
    ]

    operations = [
         migrations.RunPython(create_sample_meals),
    ]
